### ISSUE TITLE
Switching the input/label order on checkout page

### ISSUE THREAD

**Issue by EngageWP** [easydigitaldownloads/edd-mail-chimp#2] opened 2015-07-19 04:21 UTC
Hey, guys. I was playing around, recently, with the MailChimp add-on for EDD and noticed that the order of the checkbox and label it adds to the checkout page is input -> label, but the order for EDD is label -> input. While not a big deal, it creates a strange look out of the box (see attached image). Personally, I like the EDD order (label -> input) so I'd like to see the MailChimp add-on have the same order.

This would only take a few seconds to change but I'd be happy to submit a PR if this is something you'd be interested in changing.

![screen shot 2015-07-19 at 12 01 13 am](https://cloud.githubusercontent.com/assets/7537202/8764480/0eadfe86-2daa-11e5-9a93-393a1fd08038.png)

**Comment by pippinsplugins** [comment] 2015-07-20 02:15
Good catch. A PR would be great!

**Comment by EngageWP** [comment] 2015-07-20 02:44
Done

**Comment by pippinsplugins** [comment] 2015-07-20 13:27
#3

**Comment by SDavisMedia** [comment] 2015-09-01 13:15
This should be reverted. I understand the need to match core but after a lot of weighing pros and cons, it's core that needs to change. The MailChimp extension is correct.

Just for the sake of clarity, what I _believe_ happened in EDD core was a push for consistency in the checkout fields: having labels above inputs. That makes sense for text input fields but it does not for the checkboxes... at least not based on the way we display them (checkbox left, label right).

The problem is because the HTML structures were shared in core, regardless of input type, generic CSS was able to be written to handle all inputs and labels. Then Additional CSS was put in place to force the logical display of the Agree to Terms checkbox and label.

The MailChimp extension did it right and found itself looking like the outcast. Change MailChimp and that means everything else that does it right needs to change as well. Nope. EDD core needs the change and we will just have to deal with the consequences. 

In an effort to fix this all the way down through EDD core, I think the first step is reverting this commit. Then we'll turn to core and start dealing with how to handle fixing something that will affect so many themes and sites.

Reopening but let me know if I should just create a new issue.

**Comment by SDavisMedia** [comment] 2015-09-01 13:22
Related: #5

**Comment by pippinsplugins** [comment] 2015-09-01 13:56
@SDavisMedia This will also need to be updated in Aweber, and GetResponse.

**Comment by SDavisMedia** [comment] 2015-09-01 14:00
@pippinsplugins Aweber looks like it has the right structure. https://github.com/easydigitaldownloads/edd-aweber/blob/eba75838c70845d47eb1d212c00b62e9e84f116c/includes/class-edd-newsletter.php#L122 Not GetResponse, though. But I'll look at them all closely.

**Comment by pippinsplugins** [comment] 2015-09-01 14:03
:+1:

**Comment by SDavisMedia** [comment] 2015-09-12 04:16
@pippinsplugins Do we want to do a point release that just reverts this change?

**Comment by pippinsplugins** [comment] 2015-09-12 19:10
@SDavisMedia Yes please. Push when ready.

**Comment by SDavisMedia** [comment] 2015-09-13 07:18
Gonna close this again and work from issue/branch #5.

**Closed by SDavisMedia** 2015-09-13 07:18 UTC
Labels: enhancement
